[package]
name = "totpkeep"
version = "0.1.0"
authors = ["Slava Zipp <zipp.pnl@gmail.com>"]

[dependencies]
base32 = "0.3.1"
byteorder = "1.1.0"
clap = "~2.26"
oath = "0.10.2"
rand = "0.3.17"
rust-crypto = "0.2.36"

[profile.release]
lto = true
panic = 'abort'

